Fix sub model inheritance {BaseSettings => BaseModel}
As Pydantic documentation indicates:

> Sub model has to inherit from pydantic.BaseModel, Otherwise
> pydantic-settings will initialize sub model, collects values for
> sub model fields separately, and you may get unexpected results.

https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values

This was causing issues with extra characters after Pydantic {1 => 2}
upgrade because BaseSettings in Pydantic 2 defaults to extra="forbid":

    Traceback (most recent call last):
      File "<stdin>", line 6, in <module>
      File "/app/src/config/__init__.py", line 110, in <module>
        settings = Settings(
            # NOTE: We would like to hardcode the root and applications directories
        ...<24 lines>...
            ],
        )
      File "/app/.venv/lib/python3.13/site-packages/pydantic_settings/main.py", line 193, in __init__
        super().__init__(
        ~~~~~~~~~~~~~~~~^
            **__pydantic_self__._settings_build_values(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ...<27 lines>...
            )
            ^
        )
        ^
      File "/app/.venv/lib/python3.13/site-packages/pydantic/main.py", line 250, in __init__
        validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
    authentication.access_token.extra
      Extra inputs are not permitted [type=extra_forbidden, input_value='This extra nested test p... handled without error.', input_type=str]
        For further information visit https://errors.pydantic.dev/2.12/v/extra_forbidden
    authentication.extra
      Extra inputs are not permitted [type=extra_forbidden, input_value='This extra test paramete... handled without error.', input_type=str]
        For further information visit https://errors.pydantic.dev/2.12/v/extra_forbidden

Fixing {BaseSettings => BaseModel} for sub models resolved the error.