NFC: Remove unused # type: ignore
Resolves mypy error:

    error: Unused "type: ignore" comment  [unused-ignore]

Before: Found 358 errors in 11 files (checked 838 source files)
After: Found 342 errors in 7 files (checked 838 source files)