NFC: Remove unused env_prefix in MFASettings
Resolves mypy error:

    error: Extra key "env_prefix" for TypedDict "ConfigDict"  [typeddict-unknown-key]

Before: Found 342 errors in 7 files (checked 838 source files)
After: Found 341 errors in 6 files (checked 838 source files)